### ISSUE TITLE
Rating shows as rating - 0.5 if AllowHalfRating is false

### ISSUE THREAD

**Issue by cbenhagen** [sarbagyastha/flutter_rating_bar#7]
<img width="195" alt="Screenshot 2019-07-04 at 13 07 27" src="https://user-images.githubusercontent.com/814785/60662451-b3121f80-9e5c-11e9-89df-222414665215.png">

```dart
FlutterRatingBar(
    initialRating: 3,
    allowHalfRating: false,
    onRatingUpdate: (rating) {
        print(rating);
    },
)
```

**Comment by sarbagyastha** [comment]
The issue is already fixed. Will update the package tomorrow. Thank you!

**Comment by cbenhagen** [comment]
Thank you for the quick response. Where is this fixed? The latest version from github still shows this issue:

```yaml
  flutter_rating_bar:
    git:
      url: https://github.com/sarbagyastha/flutter_rating_bar.git
```

**Comment by KyllianDM** [comment]
He told you that I will update the package tommorow ;-)

**Comment by cbenhagen** [comment]
@KyllianDM There is no point uploading a new package version when the latest version in the git master still shows the error ;)

**Comment by sarbagyastha** [comment]
@cbenhagen I guess Git also features local commits 😉. It's in my office's machine and forgot to push it to GitHub. Will push and publish to pub once i get to my workspace tomorrow.

**Comment by sarbagyastha** [comment]
[Published **v1.3.0**](https://pub.dev/packages/flutter_rating_bar#130)

**Comment by cbenhagen** [comment]
Thanks!
